qcm_admin_user_resource:
    prefix: /user
    resource: @QcmAdminBundle/Resources/config/routing/user.yml

qcm_admin_user_session_resource:
    prefix: /user-session
    resource: @QcmAdminBundle/Resources/config/routing/user_session.yml

qcm_admin_category_resource:
    prefix: /category
    resource: @QcmAdminBundle/Resources/config/routing/category.yml

qcm_admin_question_resource:
    prefix: /question
    resource: @QcmAdminBundle/Resources/config/routing/question.yml

qcm_admin_answer_resource:
    prefix: /answer
    resource: @QcmAdminBundle/Resources/config/routing/answer.yml

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
