qcm_admin_user:
    prefix: /user
    resource: @QcmAdminBundle/Resources/config/routing/user.yml

qcm_admin_category:
    prefix: /category
    resource: @QcmAdminBundle/Resources/config/routing/category.yml

qcm_admin_question:
    prefix: /question
    resource: @QcmAdminBundle/Resources/config/routing/question.yml
